name       : python-pdfrw
version    : 0.4
release    : 1
source     :
    - https://github.com/pmaupin/pdfrw/archive/v0.4.tar.gz : f4da059213a0fdf8f63aa3f711cfbc25a5100333514b396f71bb90cb7bd4365f
homepage   : https://github.com/pmaupin/pdfrw
license    :
    - BSD-3-Clause
    - MIT
component  : programming.python
summary    : Python library to read and write PDF files
description: |
    pdfrw is a Python library and utility that reads and writes PDF files
build      : |
    %python3_setup
install    : |
    %python3_install
